services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    init: true
    volumes:
      - .:/workspaces/workshop
    working_dir: /workspaces/workshop
